name: Deploy App to s3

on:
    push:
        branches: [ development ]
    pull_request:
        branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v1
            - name: Install dependencies
              run: npm install
            - name: Install Angular CLI
              run: npm install -g @angular/cli --latest
            - name: Build production
              run: ng build
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
                  SOURCE_DIR: 'dist/gemini-poc'      # optional: defaults to entire repository
